global:
  frontendEnv: ""
  fullnameOverride: deploy-my-message
  namespaceOverride: ""
  nodeSelector: {}

deployment:
  labels: {}
  annotations: {}
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  image:
    repository: 192.168.179.131:5000/deploy-my-message  # 镜像仓库地址 需变更为本地
    tag: version-0.1.1
    pullPolicy: IfNotPresent
    imagePullSecrets: []
  pod:
    annotations: {}
    labels: {}
    affinity: {}
    tolerations: []
    volumes: []
    container:
      env: {}
      resources:
        limits:
          cpu: 200m
          memory: 256Mi
        requests:
          cpu: 100m
          memory: 128Mi
      volumeMounts: []
      envFrom: []
      livenessProbe: {}
      readinessProbe: {}
      startupProbe: {}
  topologySpreadConstraints: []

service:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP

ingress:
  className: nginx
  host: "test.deploy.com"
  annotations:
    nginx.ingress.kubernetes.io/app-root: /web/
  paths:
    - path: /web
      pathType: Prefix
    - path: /
      pathType: Prefix
  # paths:
  #   - path: /deploy-my-message
  #     pathType: Prefix
