global:
  frontendEnv: ""
  fullnameOverride: deploy-my-message
  namespaceOverride: ""
  nodeSelector: {}

deployment:
  image:
    repository: 192.168.179.131:5000/deploy-my-message  # 镜像仓库地址 需变更为本地
    tag: version-0.1.11
    pullPolicy: IfNotPresent
    imagePullSecrets: []