{{- if .Values.ingress }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.global.fullnameOverride }}
  {{- if .Values.global.namespaceOverride }}
  namespace: {{ .Values.global.namespaceOverride }}
  {{- end }}
  {{- if .Values.ingress.className }}
  annotations:
    {{- range $k, $v := .Values.ingress.annotations }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
  {{- end }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
  - http:
      paths:
      {{- range .Values.ingress.paths }}
      - path: {{ .path }}
        pathType: {{ .pathType }}
        backend:
          service:
            name: {{ $.Values.global.fullnameOverride }}
            port:
              number: {{ (index $.Values.service.ports 0).port }}
      {{- end }}
{{- end }}
