apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deploy-my-message-cd
  namespace: argocd
spec:
  project: deploy-my-message-project
  source:
    repoURL: http://192.168.179.131:10880/nanxiqi/deploy-my-message.git
    targetRevision: main
    path: cd
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
