apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: deploy-my-message-test
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: deploy-my-message
  source:
    repoURL: http://192.168.179.131:10880/nanxiqi/deploy-my-message.git
    targetRevision: test
    path: chart
    helm:
      values: |
        global:
          frontendEnv: test
          fullnameOverride: test-deploy-my-message
          namespaceOverride: deploy-my-message-test
        deployment:
          image:
            repository: 192.168.179.131:5000/deploy-my-message
            pullPolicy: IfNotPresent
        ingress:
          host: test.deploy.com
          annotations:
            nginx.ingress.kubernetes.io/use-regex: "true"
            nginx.ingress.kubernetes.io/rewrite-target: /web/$2
          paths:
            - path: /test-deploy-my-message(/|$)(.*)
              pathType: ImplementationSpecific
  destination:
    server: https://kubernetes.default.svc
    namespace: deploy-my-message-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
